# user config
user:
  params:
    # _class: github, id is the parameter that's going to be used in the URL
    github:
      id: dejavudwh
    zhihu:
      id: shadow-61-66

  feedList:
    # default feed
    - feedName: githubActivitiesFeed
      disable: False
      entryCount: 5
        
    - feedName: zhihuPostsFeed
      disable: False
      entryCount: 5

    # user feed
    - feedName: BlogFeed
      disable: True
      entryCount: 5
  
  apiList:
    # Built-in API, User-provided APIs for retrieving JSON have not been developed yet
    - apiName: githubRecentComit
      disable: False
      entryCount: 5


# detailed configuration of all seeds
feeds:
  # default feed
  # three messages of the feed: title, url, date
  githubActivitiesFeed:
    _class: github
    url: https://github.com/{id}.atom
    params: [id]
    style: '    - [{title}]({url}) - {date}'
    tagStartName: GITHUB:START
    tagEndName: GITHUB:END 

  zhihuPostsFeed:
    _class: zhihu
    url:  https://rsshub.app/zhihu/posts/people/{id}
    params: [id]
    style: '    - [{title}]({url}) - {date}'
    tagStartName: ZHIHUPOSTS:START
    tagEndName: ZHIHUPOSTS:END 

  # user feed
  BlogFeed: 
    _class:
    url: https://dejavudwh.cn/atom.xml
    params: []
    style: '- [{title}]({url}) - {date}'
    tagStartName: BLOGPOSTS:START
    tagEndName: BLOGPOSTS:END 


# detailed configuration of all api
# Built-in API, User-provided APIs for retrieving JSON have not been developed yet
api:
  # default api
  # TODO hard code for realize to grab the latest commit 
  allGithubRepo:
    _class: github
    url: https://api.github.com/users/{id}/repos
  allGithubCommit:
    _class: github
    url: https://api.github.com/repos/{owner}/{repo}/commits

  zhihuApi: